### ISSUE TITLE
Does not load with plugin

### ISSUE THREAD

**Issue by ericboakye** [cniesen/BukkitPluginTemplate#1]
It did not load plugin https://gyazo.com/7969f2028b14cc91d29408003a1eb9de

**Comment by cniesen** [comment]
You apparently using CraftBukkit version 1.8.7-R0.1-SNAPSHOT.  I'm not sure where you found that one.  Try the 1.7.9-R0.2 version. https://github.com/cniesen/CraftBukkit/releases/tag/1.7.9-R0.2

**Comment by cniesen** [comment]
BTW, if you're using spigot you might want to explore https://www.spigotmc.org/wiki/creating-a-blank-spigot-plugin-in-intellijidea/ and see if that does what you want.

**Comment by ericboakye** [comment]
I'm using gradle instead now, works better. Thanks.
